### ISSUE TITLE
Pass props via `React.cloneElement` conditionally

### ISSUE THREAD

**Issue by bedrich-schindler** [react-ui-org/react-ui#122]
Component where `React.cloneElement` is used, props of original component are immediately overwritten by this. It is necessary to pass props to `React.cloneElement` conditionally.

**Comment by adamkudrna** [comment]
The change should be considered case by case. Examples:

- We want to allow to disable individual `Button`s within a `ButtonGroup`.
- We **don't** want to allow to change priority and size of individual `Button`s within a `ButtonGroup` — this should be only set directly on the `ButtonGroup`.

**Comment by bedrich-schindler** [comment]
This issue is no more valid. `React.cloneElement` has been removed from all occurrences except `Modal.jsx` where it is used to inject content inside of it. Therefore I close this issue.
