### ISSUE TITLE
Add ready-to-use CSS to distribution package

### ISSUE THREAD

**Issue by adamkudrna** [react-ui-org/react-ui#197]
All we need is to **document** two styling options:

1. Import a ready-to-use compiled CSS `reactui.css`.
2. Import source Sass files from `src/scss`.

---

~~All Sass endpoints should be compiled to CSS, minified (but keep the unminified version too), and placed in `dist`:~~

- ~~`foundation(.min).css`~~
- ~~`helpers(.min).css`~~
- ~~`theme(.min).css`~~
- ~~`components(.min).css`~~

~~`src` can then be excluded from publishing. Sass source files remain intact.~~

~~Suggested Webpack plugin (maybe it's no longer the right choice): https://webpack.js.org/plugins/mini-css-extract-plugin/#minimal-example~~

**Comment by hubacekj** [comment]
The mini-css-extract-plugin still seems as the right choice, but it needs Webpack 5 to work (#358).

**Comment by mbohal** [comment]
I will work on it along with #373

**Comment by bedrich-schindler** [comment]
According to @mbohal, description is not up-to-date and need to be updated, see message in Slack.
