### ISSUE TITLE
event handler props

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#218]
Presently RUI uses `*Handler` format for passing actions to interactive components. For example we have `clickHandler`, `closeHandler` etc.  This causes the following problems:

* We have to pass this prop manually tot he native element (see: https://github.com/react-ui-org/react-ui/blob/120eaedbe2134c844ba2d987e00313015c549a3c/src/lib/components/ui/TextArea/TextArea.jsx#L99)
* It is inconsistent with other React [synthetic events](https://reactjs.org/docs/events.html) naming convention

I propose we:

* Switch `*Handler` syntax to `on*` syntax
* Pass all synthetic event handlers implicitly via `ransferProps`, that is get rid of `clickHandler` and such

This will lead to:
* removing some props (`clickHandler`, `changeHandler`, maybe others)
* renaming some non event props such as `closeHandler` to `onClose`: https://github.com/react-ui-org/react-ui/blob/456598417add3d890cd65d46ad75ac841431f7b1/src/lib/components/ui/Modal/Modal.jsx#L273

**Comment by bedrich-schindler** [comment]
I vote for renaming `clickHandler` -> `onClick` (as others), I think that this original idea with `<event>Handler` was not good. Otherwise I think that we must preserve those handlers in props. It means to rename them, not to delete them. They cannot be omit from props documentation.

**Comment by mbohal** [comment]
Decided on video call with @bedrich-schindler and @adamkudrna :

We will do it as proposed. Since `clickHandler/onClick` is not mandatory, we do not need to include it explicitly.
