### ISSUE TITLE
create helper function for adding classNames

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#270]
Presently we use the following syntax:
```
<div className={['class1', 'class2'].join(' ')} />
```

This produces empty attribute `className` if classes are added conditionally and all conditions evaluate to `flase`.

We need to create a helper function `className()` in `src/lib/services`. The usage should be:

```
<div {...className(['class1 || null', 'class2'])} />
```

it should return either `{ className: 'class1 class2' } or {} if the class list is empty.

All usages in RUI should be updated.

This function should be also available to projects depending on RUI and must be therefore well documented.

**Comment by adamkudrna** [comment]
Have we considered something like this?

```jsx
<div className={className(['class1 || null', 'class2'])} />
```

… where the `className` function would return null/undefined value that would then cause React to omit the `className` attribute. I'm not sure if it's neither better nor possible but also I'm not aware of the discussion on the syntax (which may be my fault).

**Comment by mbohal** [comment]
@adamkudrna I think I like your solution better. The `className` function would only return the actual class list and not the hardcoded `className` attribute name.

To omit the HTML attr from rendering value must be set to `undefined`.
The signature of the function must therefore be: `(array) -> string|undefined`.

Maybe we should consider a more descriptive name then? Perhaps `classNameAttribute()`? This better communicates why it returns `undefined` as opposed to more natural `null`. What does @bedrich-schindler think?
