### ISSUE TITLE
Unify API of components which have UI states variations

### ISSUE THREAD

**Issue by adamkudrna** [react-ui-org/react-ui#272]
`type="success"` vs. `variant="success"`

Somewhere it's `type` (eg. `Alert`, `Card`), somewhere `variant` (eg. `Button` – because of conflict with native `type` attribute).

**Comment by mbohal** [comment]
We need to unify:
* `propType` name
* `propType` option list
  * `success`
  * `warning`
  * `danger`
  * `help`
  * `info`
  * `note`
