### ISSUE TITLE
Change of `ScrollView` API

### ISSUE THREAD

**Issue by adamkudrna** [react-ui-org/react-ui#303]
General idea: make anything possible, but cut off "shortcut" API options. Keep API flat so it can be overridden with global props.

1. `shadowColor` might be redundant — it's possible to achieve the same result with (more complicated) `custom[Start/End]ShadowStyle`.
2. If 1 is implemented, `shadowSize` could be moved to `custom[Start/End]ShadowStyle`.
3. `custom[Start/End]ShadowStyle` might accept HTML / React component just like arrows.
3. `arrowsColor` is redundant since custom arrows are supported.
4. `custom*` options would be the only way of passing an icon or scrolling shadow, therefore the `custom` prefix is needless.

Test anything testable.

**Comment by adamkudrna** [comment]
Anything else @mbohal?

**Comment by mbohal** [comment]
@adamkudrna I think we could also get rid of the `arrows` prop and remove the default arrows. If user want arrows, they can easily provide custom implementation either by wrapping the component or by using `globalProps`.

If they do not want arrows then the can simply leave the `nextProp` and `prevProp` empty.

I see no use for another prop to control the arrows.

**Comment by adamkudrna** [comment]
> If they do not want arrows then the can simply leave the `nextProp` and `prevProp` empty.
> 
> I see no use for another prop to control the arrows.

@mbohal This is not possible, the customization props only adjust _what_ is displayed and _how_. The scrolling shadow elements and arrow buttons are still there, we only exchange their content and/or appearance. Therefore `arrows` and `shadows` (the latter is new, coming in a PR soon) toggles are necessary. Leaving `nextArrow` and `prevArrow` empty would lead to invisible arrow buttons.
