### ISSUE TITLE
Unify behavior of empty components

### ISSUE THREAD

**Issue by adamkudrna** [react-ui-org/react-ui#305]
Sometimes `children` is required, sometimes not; sometimes an empty `div` is allowed to be returned, sometimes `null` is returned. There is no obvious reason (other than individually considered DX) which is confusing.

**Comment by mbohal** [comment]
In accordance with the general idea defined in #303 :

>  make anything possible, but cut off "shortcut" API options

Maybe we should unify the beahviour on either:
1. making children mandatory
2. rendering the component even with no children

For better DX the user would be expected to wrap the component in another layer to handle the situation according to the needs of the given app.

**Comment by mbohal** [comment]
Agreed on phone call that we want to:
* UI components: children are optional and the component renders itself with no children
* UI components: children are optional and the component returns `null` with no children
