### ISSUE TITLE
`forwardedRef` is used instead of `ref`

### ISSUE THREAD

**Issue by bedrich-schindler** [react-ui-org/react-ui#385]
I would like to clarify following:

* `ref` is prop used to reference origin HTML component.
* `forwardedRef` is prop used in many our components, but it is supposed to be used as internal implementation only and must not be used as prop.

The thing is that we have HoC  `src/lib/components/withForwardedRef.jsx` that wraps original component with `React.forwardRef`. This redirects `ref` to `forwardedRef`, so every component wrapped by this HoC accepts `ref`, not `forwardedRef`.

```js
export default (WrappedComponent) => {
  const withForwardedRef = (props, ref) => (
    <WrappedComponent {...props} forwardedRef={ref} />
  );

  withForwardedRef.displayName = `withForwardedRef(${WrappedComponent.name || WrappedComponent.name})`;

  return React.forwardRef(withForwardedRef);
};
```

```js
export const Button = ({
  forwardedRef,
  ...restProps
}) => {

export const ButtonWithGlobalProps = withForwardedRef(withGlobalProps(Button, 'Button'));

export default ButtonWithGlobalProps;
```

First problem is that API shows `forwardedRef` instead of `ref`:

![image](https://user-images.githubusercontent.com/10213870/175476806-865e3d74-edba-4ee9-b1c4-710934b81397.png)

Other problem is that code examples contain different kind of imports. Sometimes default export (the correct one) is used, sometimes named export is used (the wrong one). It results in fact that almost all examples contain `forwardedRef`, but `ref` must be used in implementation, otherwise it won't work.

**Comment by mbohal** [comment]
Maybe we could change the implementation to remove `forwardedRef` from props and pass it by context.

We already use this for internal things in:

* form fields in `FormLayout` (`src/lib/components/FormLayout/FormLayoutContext.js`)
* `Button` in `ButtonGroup` (src/lib/components/ButtonGroup/ButtonGroupContext.js)

**Comment by mbohal** [comment]
Good catch @bedrich-schindler!

**Comment by adamkudrna** [comment]
Please don't forget to update docs, e.g. in `Popover`:

<img width="857" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/175773599-cc04d644-d42c-4015-b496-a6e7766367c0.png">

**Comment by mbohal** [comment]
Aslo we need to make sure that the `transferProps` position is correct.
