### ISSUE TITLE
`Modal `is broken when `FormLayout` with horizontal layout is placed into small modal

### ISSUE THREAD

**Issue by bedrich-schindler** [react-ui-org/react-ui#386]
We have to somehow solve situation when `Modal` with `size: small` is used in combination with `FormLayout` with `fieldLayout: horizontal`:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/10213870/175769933-dba8cdff-f11f-40b7-9d50-60b4ca2078e3.png">

```js
            <Modal
              closeButtonRef={modalCloseButtonRef}
              primaryButtonRef={modalPrimaryButtonRef}
            >
              <ModalHead
                onClose={() => setModalOpen(false)}
                title="Add new user"
              />
              <ModalBody>
                <ModalContent>
                  <FormLayout fieldLayout="horizontal">
                    <TextField label="Username" />
                    <TextField label="Password" type="password" />
                  </FormLayout>
                </ModalContent>
              </ModalBody>
              <ModalFooter>
                <Button
                  label="Save"
                  onClick={() => setModalOpen(false)}
                  ref={modalPrimaryButtonRef}
                />
                <Button
                  label="Close"
                  onClick={() => setModalOpen(false)}
                  priority="outline"
                  ref={modalCloseButtonRef}
                />
              </ModalFooter>
            </Modal>
```

Issue is blocked by #306

**Comment by adamkudrna** [comment]
I think `Modal` gives much more acceptable outcome now when #393 has been merged:

## `scrolling="auto"`
<img width="450" alt="auto" src="https://user-images.githubusercontent.com/5614085/180857211-63c8ea39-bc5e-4755-b120-75baa5ff620a.png">

## `scrolling="custom"` (with `ScrollView`)
<img width="514" alt="custom" src="https://user-images.githubusercontent.com/5614085/180857291-b2bcbb24-5fcc-44e2-9691-0891936eaa78.png">

## `scrolling="none"`
<img width="507" alt="none" src="https://user-images.githubusercontent.com/5614085/180857349-f2bdef12-7025-4d47-b68d-12a54aa41b80.png">

**Comment by mbohal** [comment]
With the new broken up modal (see: #306) it is not happening anymore.

**Comment by mbohal** [comment]
@bedrich-schindler will consider updating the docs

**Comment by bedrich-schindler** [comment]
I see that @adamkudrna has issue marked as `in progress`. Would you update the docs @adamkudrna or should I do it? (Last comment is bit confusing when issue is assigned to you)-

**Comment by adamkudrna** [comment]
OK, I'll do it. (I put it in progress when I started the investigation.)
