### ISSUE TITLE
Add support for `<optgroup>` to the `Select` component

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#395]

**Comment by bedrich-schindler** [comment]
I would change its `options` API to following (wrote in TS syntax to make it clear)


```
interface Option {
  disabled: boolean;
  label: string;
  value: string;
}
interface OptionGroup {
  options: Option[];
  label: string;
}

type SelectOptions = (Option | OptionGroup)[];
```

So options can accept array of both option or optgroup. And I would do if before v1.0 is released at it seems like the last thing overall we do not support across standard inputs.

cc @adamkudrna

**Comment by mbohal** [comment]
I agree with the proposal by @bedrich-schindler

It should be backward compatible, so I have no strong feelings either way about the need to have it in `v1.0`.
