### ISSUE TITLE
Update Stylelint to version 16

### ISSUE THREAD

**Issue by bedrich-schindler** [react-ui-org/react-ui#484]
Currently, stylelint@15 cannot be installed because stylelint configuration requires stylelint@14.

**Comment by adamkudrna** [comment]
https://stylelint.io/migration-guide/to-15/

**Comment by adamkudrna** [comment]
⚠️ **Caution!** Reportedly, Stylelint has dropped some stylistic rules like line length or indentation. Options to fill the gap:

1. use Prettier
2. use a plugin

1) puts our coding style slightly out of our control, so 2) seems to be a better option.

---

Thanks to @crishpeen for raising it up! ❤

**Comment by mbohal** [comment]
On video call we agreed, that we do not want to use Prettier, we do not think it is a good tool.

**Comment by mbohal** [comment]
Version 16 was released: https://github.com/stylelint/stylelint/releases/tag/16.0.0

**Comment by adamkudrna** [comment]
`@visionappscz/stylelint-config` v4.0.0-beta1 released!

https://github.com/visionappscz/stylelint-config/releases/tag/v4.0.0-beta1
