### ISSUE TITLE
Link inside form element help text has invalid cursor

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#488]
When I use a link (`<a/>`) inside a `helpText` prop of a form field (e.g. `TextField`) the cursor does not change when hovering over the link.

![image](https://github.com/react-ui-org/react-ui/assets/4589176/a93a66c2-e64a-423b-a5d9-129f497ee472)

Expected behaviour is that the cursor changes when hovering over a Link.

**Comment by adamkudrna** [comment]
Thanks for testing such a use case! However, I'm afraid the problem is in the typo you have in your example. If you change `hre` to `href`, everything works:

<img width="816" alt="obrazek" src="https://github.com/react-ui-org/react-ui/assets/5614085/d2bd70e0-48fe-40ef-8bf2-8c912c561b75">

**Comment by mbohal** [comment]
> If you change hre to href, everything works:

:facepalm:
