### ISSUE TITLE
Inherit link color in components with feedback/validation states 

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#492]
When we use the `<TextLink>` component inside an `<Alert>` element, it uses the context color (from `<Alert>`) instead of the default link color (from `<TextLink>`).

![image](https://github.com/react-ui-org/react-ui/assets/4589176/68ec1fbc-8a5c-402b-b53e-f725dc9c9cb0)

However in other contexts this is not the case for other elements:

![image](https://github.com/react-ui-org/react-ui/assets/4589176/62ec851c-a2cb-4127-ad22-eb3e4c984de3)

We need to somehow unify this behavior across all our components.

**Comment by mbohal** [comment]
@davidurban proposes that the local context color should be used everywhere where the context element can changes color to provide some information to the user.

**Comment by adamkudrna** [comment]
Thank you for your proposal. However, we need to discuss it a bit more deeply before we can dispatch it to engineering.

1. We need to clarify what means "everywhere [where the context element can changes color]". There are two relevant situations:
   1. components that use [Feedback Colors](https://react-ui.io/foundation/colors#feedback-colors) (but there components with both light (`Alert`) and dark (`Badge`) background, what then?),
   2. components that use [Validation State Colors](https://react-ui.io/foundation/colors#validation-states) (but there is also the default state, see the input on the left).
3. We need to decide if links in the default validation state should be gray too — that's a BC.
4. RUI only: should the color inheritance feature be optional globally / per component / not at all?

**Comment by davidurban** [comment]
1. Agree with both.
2. They should not be gray, but default TextLink colour (theme.colors.primary).
3. No opinion.

I also think we will need to eventually start supporting feedback colours on most components (like Paper, Modal, Tabs…) because of needs of Generated UIs. There a node (represented by Paper, or Tap) can become invalid and we will need to visually indicate it. Having ability to use Feedback Colours would greatly improve DX and consistency. In such cases, container links should also inherit the colour.

**Comment by mbohal** [comment]
> we will need to eventually start supporting feedback colours on most components (like Paper, Modal, Tabs…) 

Generally I think the same.

**Comment by adamkudrna** [comment]
| Component      | Action Colors | Feedback Colors | Neutral Colors | Validation Colors | Link Color Inheritance |
|----------------|---------------|-----------------|----------------|-------------------|------------------------|
| Alert          | —             | ✅               | ✅              | —                 | ✅                      |
| Badge          | —             | ✅               | ✅              | —                 | —                      |
| Button         | ✅             | ✅               | ✅              | —                 | —                      |
| ButtonGroup    | ✅             | ✅               | ✅              | —                 | —                      |
| Card           | —             | ✅               | ✅              | —                 | 🎯                     |
| CheckboxField  | —             | —               | —              | ✅                 | 🎯                     |
| FileInputField | —             | —               | —              | ✅                 | 🎯                     |
| FormLayout     | —             | —               | —              | —                 | —                      |
| Grid           | —             | —               | —              | —                 | —                      |
| InputGroup     | —             | —               | —              | —                 | —                      |
| Modal          | —             | #468            | —              | —                 | #468                   |
| Paper          | —             | 🔮              | —              | —                 | —                      |
| Popover        | —             | —               | —              | —                 | —                      |
| Radio          | —             | —               | —              | ✅                 | 🎯                     |
| ScrollView     | —             | —               | —              | —                 | —                      |
| SelectField    | —             | —               | —              | ✅                 | 🎯                     |
| Table          | —             | —               | —              | —                 | —                      |
| Tabs           | —             | 🔮              | —              | —                 | —                      |
| Text           | —             | —               | —              | —                 | —                      |
| TextArea       | —             | —               | —              | ✅                 | 🎯                     |
| TextField      | —             | —               | —              | ✅                 | 🎯                     |
| TextLink       | —             | —               | —              | —                 | —                      |
| Toggle         | —             | —               | —              | ✅                 | 🎯                     |
| Toolbar        | —             | —               | —              | —                 | —                      |

🎯 — to be done in this issue
🔮 — to be done in the future
