### ISSUE TITLE
`Radio` breaks `<FormLayout fieldLayout="horizontal">`

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#493]
In desktop Chrome it is broken, see screenshot.
In desktop FF it works fine.
I did not check other browsers.

![Screenshot from 2023-09-22 10-04-45](https://github.com/react-ui-org/react-ui/assets/4589176/18506bb9-7cd7-40a5-a933-1491885753e2)

It is reproducible ion the docs by https://react-ui.io/components/form-layout#full-example .

**Comment by adamkudrna** [comment]
Relates to #232. Sugrid is now supported in Chrome from version 117 (and apparently works in a different way).

**Comment by adamkudrna** [comment]
Problem seems to be in Chrome not supporting subgrid on `<fieldset>`. `<div>` works fine.
