### ISSUE TITLE
Broken layout when InputGroup is used within FormLayout

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#522]
When `<InputGroup>` is used within `<FormLayout>` it breaks when there is not enough space.

When used **outside** of `<FormLayout>` the `<InputGroup>` maintains width and overflows:

![Screenshot from 2024-01-15 18-14-21](https://github.com/react-ui-org/react-ui/assets/4589176/d3afd506-19b6-4899-b0cb-c670ffb582a5)

I think this is the correct behavior.

However when used **inside** of `<FormLayout>` and when the last element is a `<Button>` it breaks:

![Screenshot from 2024-01-15 18-14-12](https://github.com/react-ui-org/react-ui/assets/4589176/d2416620-650a-45e1-9634-8a91a503c0de)

**Comment by AhmAlkalii** [comment]
Hi can i work on this?

**Comment by mbohal** [comment]
@AhmAlkalii If you are willing to make a PR, it would be greatly appreciated.
