### ISSUE TITLE
Forgottent console log in dev mode

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#532]
This https://github.com/react-ui-org/react-ui/blob/9014fb5f2cbd752c5753f439154b91a7268a2735/src/components/_helpers/transferProps.js#L27 `console.log` should not be there.

Also, to prevent similar error in the future, we should forbid console.log statements unless explicitly allowed by `eslint-disable…` statement.

**Comment by AhmAlkalii** [comment]
hi can i work on this?

**Comment by mbohal** [comment]
@AhmAlkalii If you are willing to make a PR, it would be greatly appreciated.
