### ISSUE TITLE
Create MenuButton components

### ISSUE THREAD

**Issue by bedrich-schindler** [react-ui-org/react-ui#56]
Create MenuButton components according to following design:

![Menu button](https://user-images.githubusercontent.com/10213870/79684324-9353b880-8230-11ea-97df-874e185ee2a0.png)

**Comment by adamkudrna** [comment]
Could we please use a [more common name](https://www.google.com/search?q=split+button) `Split Button`? `Menu Button` is [more about hamburgers](https://www.google.com/search?q=menu+button)… 🍔

**Comment by mbohal** [comment]
Is this in any way related to the `ButtonGroup` component?

I could imagine that on big screens I want to see a button group and on smaller screens this. Functionally it seems like the same thing to me.

**Comment by adamkudrna** [comment]
@mbohal No, it's a different UX pattern. What you describe might be collapsible `ButtonGroup` but it's not the case here.

**Comment by mbohal** [comment]
@adamkudrna agreed to think about joining this and buttonGroup into one component (via phone call)

**Comment by adamkudrna** [comment]
Here is what I found in Weblium app. It illustrates the use case of having the top actions visible while collapsing the others.

![image](https://user-images.githubusercontent.com/5614085/82304395-8d323280-99bc-11ea-9296-f78f44deb7e1.png)

**Comment by mbohal** [comment]
@davidurban agrees that merging this with buttonGroup is acceptable

**Comment by davidurban** [comment]
Attaching updated screenshot for "you-know-which" project:

<img width="513" alt="Screenshot 2020-05-20 at 15 14 08" src="https://user-images.githubusercontent.com/8739891/82450186-a87c6b00-9aac-11ea-9aff-5a65e0b9f5c7.png">

**Comment by adamkudrna** [comment]
As agreed recently, I'm closing this issue as we don't see a use case for such a specific component.
