### ISSUE TITLE
Lint commit messages

### ISSUE THREAD

**Issue by adamkudrna** [react-ui-org/react-ui#70]
Check that commit messages are in the following format:

```
<Commit message text> (#<GitHub issue number>)
```

**Comment by adamkudrna** [comment]
It is possible [through a third-party GitHub app](https://github.com/SystangoTechnologies/commit-message-lint/wiki/Commit-Message-Lint---2.0).

On one hand, I would like to prevent commits without reference to an issue because **currently we are committing against issues only**. On the other hand, it might discourage community developers (yes, there is currently no one like that) from contributing because of too restrictive workflow — first an issue, then a PR.

I checked for Bootstrap and [they don't have any such linters set up, only issue templates](https://github.com/twbs/bootstrap/tree/master/.github).

@mbohal @bedrich-schindler What do you think?

**Comment by bedrich-schindler** [comment]
It could be handy. But I have no experience with setting up open source project, linters etc. All our projects are set up very strict. I can live with both cases ... Neverthless we are still those who merge all pull requests so we are responsible for 3rd party contributors  hence we allow to merge their work. So even if we do not activate these checks, we still be able to handle it ourselves.

**Comment by mbohal** [comment]
I would prefer not to implement this. Even for private projects this is borderline for me. For FOSS I think this is too much.
